import Head from 'next/head'
import { useState } from 'react'

const TONES = [
  { id:'professional', label:'Professional', icon:'💼' },
  { id:'enthusiastic', label:'Enthusiastic', icon:'🚀' },
  { id:'confident',    label:'Confident',    icon:'💪' },
  { id:'concise',      label:'Concise',      icon:'⚡' },
]

export default function CoverLetterPage() {
  const [form, setForm] = useState({
    name: '', currentRole: '', years: '', skills: '',
    company: '', role: '', jd: '', highlights: '', tone: 'professional',
  })
  const [loading, setLoading] = useState(false)
  const [result, setResult]   = useState(null)
  const [error, setError]     = useState('')
  const [copied, setCopied]   = useState('')
  const [activeTab, setActiveTab] = useState('letter') // letter | linkedin

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

  const generate = async (e) => {
    e?.preventDefault()
    setError(''); setResult(null); setLoading(true)
    try {
      const r = await fetch('/api/cover-letter/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...form,
          years: Number(form.years) || 0,
          skills: form.skills.split(',').map(s => s.trim()).filter(Boolean),
        }),
      })
      const data = await r.json()
      if (!r.ok || !data.ok) { setError(data.error || 'Failed'); setLoading(false); return }
      setResult(data)
    } catch (e) { setError('Network error') }
    setLoading(false)
  }

  const copy = (text, key) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(key); setTimeout(() => setCopied(''), 2000)
    })
  }

  const download = () => {
    if (!result) return
    const blob = new Blob([result.full_letter], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `cover-letter-${form.company.replace(/\s+/g,'-').toLowerCase() || 'untitled'}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const shareWA = () => {
    if (!result) return
    const msg = `📝 *Cover Letter for ${form.role || 'role'}${form.company ? ` at ${form.company}` : ''}*\n\n${result.full_letter.slice(0, 600)}...\n\n_Generated by HireHub360 AI_\nhttps://hirehub360.in/cover-letter`
    window.open('https://wa.me/?text=' + encodeURIComponent(msg), '_blank')
  }

  return (
    <>
      <Head>
        <title>AI Cover Letter Generator — Personalized in 10 Seconds | HireHub360</title>
        <meta name="description" content="Free AI cover letter generator. Paste a job description, get a tailored cover letter that mentions specific JD requirements. Email + LinkedIn versions. India's smartest job tool." />
        <link rel="canonical" href="https://hirehub360.in/cover-letter" />
        <meta property="og:title" content="AI Cover Letter Generator | HireHub360" />
        <meta property="og:description" content="Paste JD → AI writes your cover letter in 10 seconds. Tailored, specific, ready to send." />
        <meta property="og:image" content="https://hirehub360.in/api/og?t=AI+Cover+Letter+Generator&s=Personalized+in+10+seconds" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>

      <style>{`
        * { box-sizing: border-box; }
        body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, system-ui; background: #f5f5f7; }
        .input { width: 100%; padding: 11px 14px; border-radius: 10px; border: 1px solid #d1d5db; font-size: 14px; font-family: inherit; outline: none; transition: border-color .15s; }
        .input:focus { border-color: #ff6b00; box-shadow: 0 0 0 3px rgba(255,107,0,.1); }
        .label { display: block; font-size: 12px; font-weight: 600; color: #555; margin-bottom: 6px; text-transform: uppercase; letter-spacing: .3px; }
        .tone-btn { padding: 9px 14px; border-radius: 24px; border: 1.5px solid #e5e7eb; background: #fff; font-size: 13px; cursor: pointer; font-weight: 500; }
        .tone-btn.on { background: #1d1d1f; color: #fff; border-color: #1d1d1f; }
        .action-btn { background: rgba(255,255,255,.15); color: #fff; border: 1px solid rgba(255,255,255,.2); padding: 8px 14px; border-radius: 8px; font-size: 13px; font-weight: 600; cursor: pointer; }
        .action-btn:hover { background: rgba(255,255,255,.25); }
        .pre-letter { white-space: pre-wrap; font-family: Georgia, 'Times New Roman', serif; font-size: 15px; line-height: 1.75; color: #1d1d1f; }
        @media print { .no-print { display: none !important; } body { background: #fff !important; } }
        @media(max-width:700px){ .form-grid { grid-template-columns: 1fr !important; } }
      `}</style>

      <nav className="no-print" style={{ background: '#fff', borderBottom: '1px solid #e5e7eb', padding: '0 24px', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 100 }}>
        <a href="/" style={{ textDecoration: 'none', fontSize: 18, fontWeight: 800, color: '#1d1d1f' }}>HireHub<span style={{ color: '#ff6b00' }}>Hub</span><sup style={{ fontSize: 10 }}>360</sup></a>
        <div style={{ display: 'flex', gap: 14 }}>
          <a href="/" style={{ textDecoration: 'none', fontSize: 13, color: '#666' }}>Jobs</a>
          <a href="/resume-upload" style={{ textDecoration: 'none', fontSize: 13, color: '#666' }}>Resume Parser</a>
          <a href="/interview-prep" style={{ textDecoration: 'none', fontSize: 13, color: '#666' }}>Interview Prep</a>
          <a href="/post-job" style={{ background: '#ff6b00', color: '#fff', textDecoration: 'none', padding: '7px 16px', borderRadius: 8, fontSize: 13, fontWeight: 600 }}>Post Job</a>
        </div>
      </nav>

      <div className="no-print" style={{ background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)', padding: '50px 24px', textAlign: 'center', color: '#fff' }}>
        <div style={{ display: 'inline-block', background: 'rgba(255,255,255,.15)', borderRadius: 20, padding: '5px 16px', fontSize: 13, marginBottom: 14, fontWeight: 600 }}>✨ Free · AI-Powered · 10 Seconds</div>
        <h1 style={{ margin: '0 0 12px', fontSize: 36, fontWeight: 800 }}>AI Cover Letter Generator</h1>
        <p style={{ margin: 0, fontSize: 16, color: 'rgba(255,255,255,.85)' }}>Paste the JD, add a few details — get a tailored cover letter that mentions the company by name.</p>
      </div>

      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '32px 20px 80px' }}>
        {!result && (
          <form onSubmit={generate} className="no-print" style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 14, padding: 28 }}>
            <div className="form-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
              <div>
                <label className="label">Your Name *</label>
                <input className="input" value={form.name} onChange={e => set('name', e.target.value)} placeholder="e.g. Priya Sharma" required />
              </div>
              <div>
                <label className="label">Current Role</label>
                <input className="input" value={form.currentRole} onChange={e => set('currentRole', e.target.value)} placeholder="e.g. Senior Frontend Engineer" />
              </div>
              <div>
                <label className="label">Years of Experience</label>
                <input className="input" type="number" min="0" max="40" value={form.years} onChange={e => set('years', e.target.value)} placeholder="e.g. 5" />
              </div>
              <div>
                <label className="label">Key Skills (comma-separated)</label>
                <input className="input" value={form.skills} onChange={e => set('skills', e.target.value)} placeholder="React, Node.js, AWS, TypeScript" />
              </div>
              <div>
                <label className="label">Target Company</label>
                <input className="input" value={form.company} onChange={e => set('company', e.target.value)} placeholder="e.g. Razorpay" />
              </div>
              <div>
                <label className="label">Target Role</label>
                <input className="input" value={form.role} onChange={e => set('role', e.target.value)} placeholder="e.g. Staff Engineer - Payments" />
              </div>
            </div>

            <div style={{ marginBottom: 16 }}>
              <label className="label">Job Description (paste the full JD) *</label>
              <textarea className="input" value={form.jd} onChange={e => set('jd', e.target.value)} rows={6} required
                placeholder="Paste the complete job description here. The more detail, the better the cover letter..." style={{ resize: 'vertical', minHeight: 120 }} />
            </div>

            <div style={{ marginBottom: 16 }}>
              <label className="label">Your Key Achievements / Notes (optional)</label>
              <textarea className="input" value={form.highlights} onChange={e => set('highlights', e.target.value)} rows={3}
                placeholder="e.g. Led migration of legacy system serving 10M users · Mentored 4 engineers · Built core checkout flow" style={{ resize: 'vertical' }} />
            </div>

            <div style={{ marginBottom: 22 }}>
              <label className="label">Tone</label>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                {TONES.map(t => (
                  <button key={t.id} type="button" onClick={() => set('tone', t.id)} className={`tone-btn ${form.tone === t.id ? 'on' : ''}`}>
                    {t.icon} {t.label}
                  </button>
                ))}
              </div>
            </div>

            {error && <div style={{ background: '#fef2f2', border: '1px solid #fca5a5', color: '#dc2626', padding: '11px 14px', borderRadius: 10, marginBottom: 16, fontSize: 14 }}>❌ {error}</div>}

            <button type="submit" disabled={loading} style={{ width: '100%', background: loading ? '#9ca3af' : 'linear-gradient(135deg, #4f46e5, #7c3aed)', color: '#fff', border: 'none', padding: '15px', borderRadius: 12, fontSize: 16, fontWeight: 700, cursor: loading ? 'wait' : 'pointer' }}>
              {loading ? '✨ Generating your cover letter…' : '✨ Generate Cover Letter'}
            </button>
            <p style={{ margin: '12px 0 0', fontSize: 12, color: '#888', textAlign: 'center' }}>Takes 8-12 seconds · 100% free · No signup required</p>
          </form>
        )}

        {result && (
          <div>
            {/* Header bar */}
            <div className="no-print" style={{ background: 'linear-gradient(135deg, #4f46e5, #7c3aed)', borderRadius: 14, padding: '22px 24px', marginBottom: 20, color: '#fff' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 14 }}>
                <div>
                  <p style={{ margin: '0 0 4px', fontSize: 13, color: 'rgba(255,255,255,.7)', textTransform: 'uppercase', fontWeight: 600 }}>Match Score</p>
                  <p style={{ margin: 0, fontSize: 32, fontWeight: 800 }}>{result.match_score}/100</p>
                </div>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                  <button className="action-btn" onClick={() => copy(result.full_letter, 'letter')}>{copied === 'letter' ? '✅ Copied' : '📋 Copy'}</button>
                  <button className="action-btn" onClick={download}>⬇️ Download</button>
                  <button className="action-btn" onClick={() => window.print()}>🖨 Print</button>
                  <button className="action-btn" onClick={shareWA}>📱 WhatsApp</button>
                  <button className="action-btn" onClick={() => setResult(null)}>↩ New letter</button>
                </div>
              </div>
            </div>

            {/* Tabs */}
            <div className="no-print" style={{ display: 'flex', gap: 4, marginBottom: 14, background: '#e5e7eb', padding: 4, borderRadius: 10, width: 'fit-content' }}>
              <button onClick={() => setActiveTab('letter')} style={{ background: activeTab === 'letter' ? '#fff' : 'transparent', border: 'none', padding: '7px 16px', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>📧 Cover Letter</button>
              <button onClick={() => setActiveTab('linkedin')} style={{ background: activeTab === 'linkedin' ? '#fff' : 'transparent', border: 'none', padding: '7px 16px', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>💼 LinkedIn DM</button>
            </div>

            {activeTab === 'letter' && (
              <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 14, padding: '36px 40px', marginBottom: 20 }}>
                {result.subject_line && (
                  <div className="no-print" style={{ background: '#fafafa', border: '1px solid #e5e7eb', borderRadius: 8, padding: '10px 14px', marginBottom: 24, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
                    <div style={{ minWidth: 0, flex: 1 }}>
                      <p style={{ margin: '0 0 2px', fontSize: 11, color: '#888', fontWeight: 600, textTransform: 'uppercase' }}>Subject</p>
                      <p style={{ margin: 0, fontSize: 14, fontWeight: 600, color: '#1d1d1f', overflow: 'hidden', textOverflow: 'ellipsis' }}>{result.subject_line}</p>
                    </div>
                    <button onClick={() => copy(result.subject_line, 'subj')} style={{ background: '#fff', border: '1px solid #d1d5db', padding: '6px 12px', borderRadius: 6, fontSize: 12, cursor: 'pointer' }}>{copied === 'subj' ? '✅' : '📋'}</button>
                  </div>
                )}
                <div className="pre-letter">{result.full_letter}</div>
              </div>
            )}

            {activeTab === 'linkedin' && result.linkedin_message && (
              <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 14, padding: '24px 28px', marginBottom: 20 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                  <p style={{ margin: 0, fontSize: 12, color: '#888', fontWeight: 600, textTransform: 'uppercase' }}>LinkedIn Message · {result.linkedin_message.length} chars</p>
                  <button onClick={() => copy(result.linkedin_message, 'li')} style={{ background: '#0a66c2', color: '#fff', border: 'none', padding: '6px 14px', borderRadius: 6, fontSize: 12, cursor: 'pointer', fontWeight: 600 }}>{copied === 'li' ? '✅ Copied' : '📋 Copy'}</button>
                </div>
                <p style={{ margin: 0, fontSize: 14, lineHeight: 1.7, color: '#1d1d1f' }}>{result.linkedin_message}</p>
              </div>
            )}

            {/* Insights */}
            <div className="no-print" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 14, marginBottom: 24 }}>
              {result.key_strengths_highlighted?.length > 0 && (
                <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 12, padding: 20 }}>
                  <p style={{ margin: '0 0 12px', fontSize: 14, fontWeight: 700, color: '#1d1d1f' }}>💪 Key Strengths Highlighted</p>
                  <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13, color: '#444', lineHeight: 1.8 }}>
                    {result.key_strengths_highlighted.map((s, i) => <li key={i}>{s}</li>)}
                  </ul>
                </div>
              )}
              {result.tips_to_strengthen?.length > 0 && (
                <div style={{ background: '#fffbeb', border: '1px solid #fcd34d', borderRadius: 12, padding: 20 }}>
                  <p style={{ margin: '0 0 12px', fontSize: 14, fontWeight: 700, color: '#92400e' }}>💡 Make it even stronger</p>
                  <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13, color: '#78350f', lineHeight: 1.8 }}>
                    {result.tips_to_strengthen.map((t, i) => <li key={i}>{t}</li>)}
                  </ul>
                </div>
              )}
            </div>

            <div className="no-print" style={{ background: 'linear-gradient(135deg, #fff7ed, #fff)', border: '1px solid #fed7aa', borderRadius: 14, padding: 24, textAlign: 'center' }}>
              <p style={{ margin: '0 0 6px', fontSize: 16, fontWeight: 700 }}>Ready to apply? 🚀</p>
              <p style={{ margin: '0 0 16px', fontSize: 14, color: '#666' }}>Browse {form.company ? `${form.company} jobs` : 'open positions'} on HireHub360.</p>
              <div style={{ display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap' }}>
                <a href={form.company ? `/company/${form.company.toLowerCase().replace(/\s+/g,'-')}` : '/'} style={{ background: '#ff6b00', color: '#fff', textDecoration: 'none', padding: '10px 22px', borderRadius: 10, fontSize: 14, fontWeight: 700 }}>Browse Jobs →</a>
                <a href="/interview-prep" style={{ background: '#1d1d1f', color: '#fff', textDecoration: 'none', padding: '10px 22px', borderRadius: 10, fontSize: 14, fontWeight: 600 }}>🎯 Prep for interview</a>
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  )
}
