import Head from 'next/head'
import { useState } from 'react'

const POPULAR_TRANSITIONS = [
  { from: 'Software Engineer',  to: 'Engineering Manager' },
  { from: 'Frontend Developer', to: 'Full Stack Developer' },
  { from: 'Data Analyst',       to: 'Data Scientist' },
  { from: 'QA Engineer',        to: 'SDET / Automation Engineer' },
  { from: 'Marketing Executive',to: 'Product Manager' },
  { from: 'Sales Executive',    to: 'Account Manager' },
  { from: 'Backend Developer',  to: 'DevOps Engineer' },
  { from: 'HR Executive',       to: 'HR Business Partner' },
]

const PRI_STYLE = {
  'Critical':    { bg:'#fef2f2', color:'#dc2626', label:'🔥 Critical' },
  'Important':   { bg:'#fff7ed', color:'#9a3412', label:'⭐ Important' },
  'Nice-to-have':{ bg:'#f0fdf4', color:'#166534', label:'💡 Nice-to-have' },
}
const DIFF_STYLE = {
  'Easy':      { bg:'#dcfce7', color:'#166534' },
  'Moderate':  { bg:'#fef9c3', color:'#854d0e' },
  'Hard':      { bg:'#fed7aa', color:'#9a3412' },
  'Very Hard': { bg:'#fecaca', color:'#dc2626' },
}

function ScoreRing({ score, size = 100 }) {
  const color = score >= 75 ? '#10b981' : score >= 50 ? '#f59e0b' : score >= 30 ? '#f97316' : '#ef4444'
  const r = (size - 14) / 2
  return (
    <div style={{ position:'relative', width:size, height:size, flexShrink:0 }}>
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="#e5e7eb" strokeWidth="9"/>
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="9"
          strokeDasharray={`${2*Math.PI*r}`}
          strokeDashoffset={`${2*Math.PI*r*(1-score/100)}`}
          strokeLinecap="round"
          transform={`rotate(-90 ${size/2} ${size/2})`}
          style={{ transition:'stroke-dashoffset 1s' }}/>
      </svg>
      <div style={{ position:'absolute', inset:0, display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center' }}>
        <span style={{ fontSize:size*0.28, fontWeight:800, color, lineHeight:1 }}>{score}</span>
        <span style={{ fontSize:11, color:'#888', marginTop:2 }}>READY</span>
      </div>
    </div>
  )
}

export default function SkillGap() {
  const [form, setForm] = useState({ currentRole:'', currentSkills:'', years:'', targetRole:'', targetCompany:'', timeline:'6 months' })
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError]   = useState('')

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

  const useTransition = (t) => {
    setForm(f => ({ ...f, currentRole: t.from, targetRole: t.to }))
  }

  const analyze = async (e) => {
    e?.preventDefault()
    setError(''); setResult(null); setLoading(true)
    try {
      const r = await fetch('/api/skills/gap', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...form,
          years: Number(form.years) || 0,
          currentSkills: form.currentSkills.split(',').map(s => s.trim()).filter(Boolean),
        }),
      })
      const data = await r.json()
      if (!r.ok || !data.ok) { setError(data.error || 'Failed'); setLoading(false); return }
      setResult(data)
      setTimeout(() => window.scrollTo({ top: 0, behavior: 'smooth' }), 100)
    } catch { setError('Network error. Try again.') }
    setLoading(false)
  }

  const shareWA = () => {
    if (!result) return
    const msg = `📈 *My Career Gap Plan: ${form.currentRole} → ${form.targetRole}*\n\nReadiness: ${result.readiness_score}/100\nTimeline: ${result.realistic_timeline}\nSalary jump: ${result.salary_jump_expected}\n\nTop skills to learn:\n${(result.skills_to_learn || []).slice(0, 5).map(s => `• ${s.skill}`).join('\n')}\n\n_Generated by HireHub360 AI_\nhttps://hirehub360.in/skill-gap`
    window.open('https://wa.me/?text=' + encodeURIComponent(msg), '_blank')
  }

  return (
    <>
      <Head>
        <title>AI Skill Gap Analyzer — Career Transition Roadmap | HireHub360</title>
        <meta name="description" content="Free AI tool: enter your current role and dream role, get a personalized skill gap analysis with month-by-month learning roadmap, free resources, and project ideas." />
        <link rel="canonical" href="https://hirehub360.in/skill-gap" />
        <meta property="og:title" content="AI Skill Gap Analyzer | HireHub360" />
        <meta property="og:description" content="Current role → dream role: AI builds your personalised learning roadmap in 15 seconds." />
        <meta property="og:image" content="https://hirehub360.in/api/og?t=AI+Skill+Gap+Analyzer&s=Current+role+%E2%86%92+Dream+role+roadmap" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>

      <style>{`
        * { box-sizing: border-box; }
        body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, system-ui; background: #f5f5f7; color:#1d1d1f; }
        .input { width:100%; padding:11px 14px; border-radius:10px; border:1px solid #d1d5db; font-size:14px; font-family:inherit; outline:none; transition:border-color .15s; }
        .input:focus { border-color:#0ea5e9; box-shadow:0 0 0 3px rgba(14,165,233,.1); }
        .label { display:block; font-size:12px; font-weight:700; color:#555; margin-bottom:6px; text-transform:uppercase; letter-spacing:.3px; }
        .chip { padding:8px 14px; border-radius:24px; border:1.5px solid #e5e7eb; background:#fff; font-size:13px; cursor:pointer; font-weight:500; }
        .chip.on { background:#0ea5e9; color:#fff; border-color:#0ea5e9; }
        .month-card { background:#fff; border:1px solid #e5e7eb; border-radius:12px; padding:18px 20px; }
        @media(max-width:700px){ .two-col { grid-template-columns:1fr !important; } }
      `}</style>

      <nav style={{ background:'#fff', borderBottom:'1px solid #e5e7eb', padding:'0 24px', height:56, display:'flex', alignItems:'center', justifyContent:'space-between', position:'sticky', top:0, zIndex:100 }}>
        <a href="/" style={{ textDecoration:'none', fontSize:18, fontWeight:800 }}>HireHub<span style={{ color:'#ff6b00' }}>Hub</span><sup style={{ fontSize:10 }}>360</sup></a>
        <div style={{ display:'flex', gap:14 }}>
          <a href="/interview-prep" style={{ textDecoration:'none', fontSize:13, color:'#666' }}>Interview Prep</a>
          <a href="/salary-calculator" style={{ textDecoration:'none', fontSize:13, color:'#666' }}>Salary</a>
          <a href="/" style={{ background:'#ff6b00', color:'#fff', textDecoration:'none', padding:'7px 16px', borderRadius:8, fontSize:13, fontWeight:600 }}>Browse Jobs</a>
        </div>
      </nav>

      {/* Hero */}
      <div style={{ background:'linear-gradient(135deg, #075985 0%, #0ea5e9 100%)', padding:'50px 24px', textAlign:'center', color:'#fff' }}>
        <div style={{ display:'inline-block', background:'rgba(255,255,255,.15)', borderRadius:20, padding:'5px 16px', fontSize:13, fontWeight:600, marginBottom:14 }}>🎯 Free · AI-Powered · Personalised</div>
        <h1 style={{ margin:'0 0 12px', fontSize:36, fontWeight:800 }}>AI Skill Gap Analyzer</h1>
        <p style={{ margin:0, fontSize:16, color:'rgba(255,255,255,.85)', maxWidth:580, marginInline:'auto' }}>Tell AI your current role and dream role — get a month-by-month learning roadmap with resources and project ideas.</p>
      </div>

      <div style={{ maxWidth:1100, margin:'0 auto', padding:'32px 20px 80px' }}>
        {!result && (
          <form onSubmit={analyze} style={{ background:'#fff', border:'1px solid #e5e7eb', borderRadius:14, padding:28 }}>
            {/* Popular transitions */}
            <div style={{ marginBottom:18 }}>
              <p style={{ margin:'0 0 8px', fontSize:12, fontWeight:700, color:'#555', textTransform:'uppercase' }}>Popular transitions (click to autofill)</p>
              <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>
                {POPULAR_TRANSITIONS.map((t, i) => (
                  <button key={i} type="button" onClick={() => useTransition(t)} style={{ background:'#f0f9ff', border:'1px solid #bae6fd', color:'#075985', padding:'6px 12px', borderRadius:20, fontSize:12, cursor:'pointer', fontWeight:500 }}>
                    {t.from} → {t.to}
                  </button>
                ))}
              </div>
            </div>

            <div className="two-col" style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14, marginBottom:14 }}>
              <div>
                <label className="label">Current Role *</label>
                <input className="input" value={form.currentRole} onChange={e => set('currentRole', e.target.value)} placeholder="e.g. Frontend Developer" required/>
              </div>
              <div>
                <label className="label">Target Role *</label>
                <input className="input" value={form.targetRole} onChange={e => set('targetRole', e.target.value)} placeholder="e.g. Full Stack Engineer" required/>
              </div>
              <div>
                <label className="label">Years of Experience</label>
                <input className="input" type="number" min="0" max="40" value={form.years} onChange={e => set('years', e.target.value)} placeholder="e.g. 3"/>
              </div>
              <div>
                <label className="label">Target Company (optional)</label>
                <input className="input" value={form.targetCompany} onChange={e => set('targetCompany', e.target.value)} placeholder="e.g. Razorpay, Swiggy"/>
              </div>
            </div>

            <div style={{ marginBottom:16 }}>
              <label className="label">Current Skills (comma-separated)</label>
              <input className="input" value={form.currentSkills} onChange={e => set('currentSkills', e.target.value)} placeholder="React, JavaScript, HTML, CSS, Git, REST APIs"/>
            </div>

            <div style={{ marginBottom:22 }}>
              <label className="label">Timeline</label>
              <div style={{ display:'flex', gap:8, flexWrap:'wrap' }}>
                {['3 months','6 months','1 year'].map(t => (
                  <button key={t} type="button" onClick={() => set('timeline', t)} className={`chip ${form.timeline === t ? 'on' : ''}`}>{t}</button>
                ))}
              </div>
            </div>

            {error && <div style={{ background:'#fef2f2', border:'1px solid #fca5a5', color:'#dc2626', padding:'11px 14px', borderRadius:10, marginBottom:14, fontSize:14 }}>❌ {error}</div>}

            <button type="submit" disabled={loading} style={{ width:'100%', background: loading ? '#9ca3af' : 'linear-gradient(135deg, #075985, #0ea5e9)', color:'#fff', border:'none', padding:15, borderRadius:12, fontSize:16, fontWeight:700, cursor: loading ? 'wait' : 'pointer' }}>
              {loading ? '🧠 Analyzing your skill gap…' : '🎯 Analyze My Skill Gap'}
            </button>
            <p style={{ margin:'10px 0 0', fontSize:12, color:'#888', textAlign:'center' }}>Takes ~15 seconds · Personalised to your timeline & target</p>
          </form>
        )}

        {result && (
          <div>
            {/* Header */}
            <div style={{ background:'linear-gradient(135deg, #075985, #0ea5e9)', borderRadius:14, padding:'24px 28px', marginBottom:20, color:'#fff' }}>
              <div style={{ display:'flex', gap:24, alignItems:'center', flexWrap:'wrap' }}>
                <ScoreRing score={result.readiness_score || 0}/>
                <div style={{ flex:1, minWidth:240 }}>
                  <p style={{ margin:'0 0 6px', fontSize:13, color:'rgba(255,255,255,.7)', textTransform:'uppercase', fontWeight:600 }}>
                    {form.currentRole} → {form.targetRole}
                  </p>
                  <p style={{ margin:'0 0 12px', fontSize:18, fontWeight:700, lineHeight:1.4 }}>{result.verdict}</p>
                  <div style={{ display:'flex', gap:8, flexWrap:'wrap', fontSize:12 }}>
                    {result.transition_difficulty && (() => {
                      const s = DIFF_STYLE[result.transition_difficulty] || { bg:'rgba(255,255,255,.18)', color:'#fff' }
                      return <span style={{ background:s.bg, color:s.color, padding:'4px 12px', borderRadius:20, fontWeight:700 }}>{result.transition_difficulty}</span>
                    })()}
                    {result.realistic_timeline && <span style={{ background:'rgba(255,255,255,.18)', padding:'4px 12px', borderRadius:20 }}>⏱ {result.realistic_timeline}</span>}
                    {result.salary_jump_expected && <span style={{ background:'rgba(16,185,129,.4)', padding:'4px 12px', borderRadius:20, fontWeight:700 }}>💰 {result.salary_jump_expected}</span>}
                  </div>
                </div>
                <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                  <button onClick={shareWA} style={{ background:'#25D366', color:'#fff', border:'none', padding:'9px 16px', borderRadius:8, fontSize:13, fontWeight:600, cursor:'pointer' }}>📱 Share</button>
                  <button onClick={() => window.print()} style={{ background:'rgba(255,255,255,.15)', color:'#fff', border:'1px solid rgba(255,255,255,.25)', padding:'9px 16px', borderRadius:8, fontSize:13, fontWeight:600, cursor:'pointer' }}>🖨 Print</button>
                  <button onClick={() => { setResult(null); setForm({ ...form }) }} style={{ background:'rgba(255,255,255,.15)', color:'#fff', border:'1px solid rgba(255,255,255,.25)', padding:'9px 16px', borderRadius:8, fontSize:13, fontWeight:600, cursor:'pointer' }}>↩ New</button>
                </div>
              </div>
            </div>

            {/* Transferable + Skills to learn */}
            <div className="two-col" style={{ display:'grid', gridTemplateColumns:'1fr 1.5fr', gap:16, marginBottom:20 }}>
              {result.transferable_skills?.length > 0 && (
                <div style={{ background:'#f0fdf4', border:'1px solid #bbf7d0', borderRadius:12, padding:'18px 20px' }}>
                  <p style={{ margin:'0 0 12px', fontSize:14, fontWeight:700, color:'#166534' }}>✓ Skills that transfer</p>
                  <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
                    {result.transferable_skills.map((t, i) => (
                      <div key={i}>
                        <p style={{ margin:'0 0 2px', fontSize:13, fontWeight:700, color:'#1d1d1f' }}>{t.skill}</p>
                        <p style={{ margin:0, fontSize:12, color:'#444', lineHeight:1.5 }}>{t.relevance}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              {result.skills_to_learn?.length > 0 && (
                <div style={{ background:'#fff', border:'1px solid #e5e7eb', borderRadius:12, padding:'18px 20px' }}>
                  <p style={{ margin:'0 0 12px', fontSize:14, fontWeight:700 }}>🎯 Skills to learn ({result.skills_to_learn.length})</p>
                  <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
                    {result.skills_to_learn.map((s, i) => {
                      const p = PRI_STYLE[s.priority] || PRI_STYLE['Important']
                      return (
                        <div key={i} style={{ display:'flex', gap:10, alignItems:'flex-start', paddingBottom:10, borderBottom: i < result.skills_to_learn.length - 1 ? '1px solid #f3f4f6' : 'none' }}>
                          <div style={{ flex:1, minWidth:0 }}>
                            <div style={{ display:'flex', gap:6, alignItems:'center', flexWrap:'wrap', marginBottom:3 }}>
                              <span style={{ fontSize:14, fontWeight:700, color:'#1d1d1f' }}>{s.skill}</span>
                              <span style={{ background:p.bg, color:p.color, padding:'1px 8px', borderRadius:10, fontSize:11, fontWeight:700 }}>{p.label}</span>
                              {s.weeks_to_learn && <span style={{ color:'#888', fontSize:11 }}>~{s.weeks_to_learn} wks</span>}
                            </div>
                            <p style={{ margin:0, fontSize:12, color:'#666', lineHeight:1.5 }}>{s.why}</p>
                          </div>
                        </div>
                      )
                    })}
                  </div>
                </div>
              )}
            </div>

            {/* Skills to deepen */}
            {result.skills_to_deepen?.length > 0 && (
              <div style={{ background:'#fff', border:'1px solid #e5e7eb', borderRadius:12, padding:'18px 20px', marginBottom:20 }}>
                <p style={{ margin:'0 0 12px', fontSize:14, fontWeight:700 }}>📈 Skills to level up</p>
                <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(220px, 1fr))', gap:10 }}>
                  {result.skills_to_deepen.map((s, i) => (
                    <div key={i} style={{ background:'#f9fafb', borderRadius:10, padding:'12px 14px' }}>
                      <p style={{ margin:'0 0 4px', fontSize:14, fontWeight:700 }}>{s.skill}</p>
                      <p style={{ margin:0, fontSize:12, color:'#666' }}>{s.current_level} → <span style={{ color:'#0ea5e9', fontWeight:700 }}>{s.target_level}</span></p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Learning path */}
            {result.learning_path?.length > 0 && (
              <div style={{ marginBottom:24 }}>
                <h2 style={{ margin:'0 0 14px', fontSize:20, fontWeight:800 }}>📅 Month-by-month learning path</h2>
                <div style={{ display:'flex', flexDirection:'column', gap:12 }}>
                  {result.learning_path.map((m, i) => (
                    <div key={i} className="month-card">
                      <div style={{ display:'flex', alignItems:'center', gap:14, marginBottom:10 }}>
                        <div style={{ width:48, height:48, background:'linear-gradient(135deg, #075985, #0ea5e9)', color:'#fff', borderRadius:10, display:'flex', alignItems:'center', justifyContent:'center', fontWeight:800, fontSize:18, flexShrink:0 }}>M{m.month}</div>
                        <div style={{ flex:1, minWidth:0 }}>
                          <p style={{ margin:'0 0 2px', fontSize:15, fontWeight:700, color:'#1d1d1f' }}>{m.focus}</p>
                          {m.hours_per_week > 0 && <p style={{ margin:0, fontSize:12, color:'#888' }}>⏱ {m.hours_per_week} hrs/week recommended</p>}
                        </div>
                      </div>
                      {m.skills?.length > 0 && (
                        <div style={{ display:'flex', flexWrap:'wrap', gap:5, marginBottom:8 }}>
                          {m.skills.map((sk, j) => <span key={j} style={{ background:'#eff6ff', color:'#1e40af', padding:'3px 10px', borderRadius:12, fontSize:12, fontWeight:500 }}>{sk}</span>)}
                        </div>
                      )}
                      {m.milestone && <p style={{ margin:0, fontSize:13, color:'#166534', background:'#f0fdf4', borderRadius:8, padding:'8px 12px' }}>🏆 <strong>By end of Month {m.month}:</strong> {m.milestone}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Resources two-column */}
            <div className="two-col" style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:16, marginBottom:20 }}>
              {result.free_resources?.length > 0 && (
                <div style={{ background:'#fff', border:'1px solid #e5e7eb', borderRadius:12, padding:'18px 20px' }}>
                  <p style={{ margin:'0 0 12px', fontSize:14, fontWeight:700 }}>🆓 Free resources</p>
                  <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                    {result.free_resources.map((r, i) => (
                      <div key={i} style={{ paddingBottom:8, borderBottom: i < result.free_resources.length - 1 ? '1px solid #f3f4f6' : 'none' }}>
                        <p style={{ margin:'0 0 2px', fontSize:13, fontWeight:700 }}>{r.name}</p>
                        <p style={{ margin:0, fontSize:11, color:'#888' }}>{r.provider} · {r.type} · {r.topic}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              {result.paid_resources?.length > 0 && (
                <div style={{ background:'#fff', border:'1px solid #e5e7eb', borderRadius:12, padding:'18px 20px' }}>
                  <p style={{ margin:'0 0 12px', fontSize:14, fontWeight:700 }}>💎 Paid resources (worth it)</p>
                  <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
                    {result.paid_resources.map((r, i) => (
                      <div key={i} style={{ paddingBottom:8, borderBottom: i < result.paid_resources.length - 1 ? '1px solid #f3f4f6' : 'none' }}>
                        <p style={{ margin:'0 0 2px', fontSize:13, fontWeight:700, display:'flex', justifyContent:'space-between' }}>
                          <span>{r.name}</span>
                          {r.price_inr && <span style={{ color:'#10b981', fontSize:12 }}>{r.price_inr}</span>}
                        </p>
                        <p style={{ margin:0, fontSize:11, color:'#888' }}>{r.provider} · {r.topic}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Projects */}
            {result.projects_to_build?.length > 0 && (
              <div style={{ background:'#fff7ed', border:'1px solid #fed7aa', borderRadius:12, padding:'18px 20px', marginBottom:20 }}>
                <p style={{ margin:'0 0 12px', fontSize:14, fontWeight:700, color:'#9a3412' }}>🛠 Projects to build for your portfolio</p>
                <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(260px, 1fr))', gap:10 }}>
                  {result.projects_to_build.map((p, i) => (
                    <div key={i} style={{ background:'#fff', borderRadius:10, padding:'12px 14px' }}>
                      <div style={{ display:'flex', justifyContent:'space-between', gap:6, marginBottom:4 }}>
                        <p style={{ margin:0, fontSize:13, fontWeight:700 }}>{p.title}</p>
                        {p.github_difficulty && <span style={{ fontSize:10, color:'#888' }}>{p.github_difficulty}</span>}
                      </div>
                      <p style={{ margin:'0 0 6px', fontSize:12, color:'#666', lineHeight:1.5 }}>{p.description}</p>
                      <div style={{ display:'flex', flexWrap:'wrap', gap:4 }}>
                        {p.skills_demonstrated?.map((s, j) => <span key={j} style={{ background:'#fafafa', color:'#666', padding:'2px 8px', borderRadius:10, fontSize:10 }}>{s}</span>)}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* First 30 days */}
            {result.first_30_days_action?.length > 0 && (
              <div style={{ background:'linear-gradient(135deg, #1d1d1f, #075985)', color:'#fff', borderRadius:12, padding:'20px 24px', marginBottom:20 }}>
                <p style={{ margin:'0 0 12px', fontSize:14, fontWeight:700, textTransform:'uppercase', letterSpacing:'.4px' }}>🚀 Start tomorrow: First 30 days</p>
                <ol style={{ margin:0, paddingLeft:18, fontSize:14, lineHeight:1.8 }}>
                  {result.first_30_days_action.map((a, i) => <li key={i}>{a}</li>)}
                </ol>
              </div>
            )}

            {/* Common mistakes + Certs + People */}
            <div className="two-col" style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:16, marginBottom:20 }}>
              {result.common_mistakes?.length > 0 && (
                <div style={{ background:'#fef2f2', border:'1px solid #fca5a5', borderRadius:12, padding:'16px 20px' }}>
                  <p style={{ margin:'0 0 10px', fontSize:13, fontWeight:700, color:'#dc2626' }}>⚠️ Avoid these common mistakes</p>
                  <ul style={{ margin:0, paddingLeft:18, fontSize:13, color:'#7f1d1d', lineHeight:1.7 }}>
                    {result.common_mistakes.map((m, i) => <li key={i}>{m}</li>)}
                  </ul>
                </div>
              )}
              <div style={{ background:'#fff', border:'1px solid #e5e7eb', borderRadius:12, padding:'16px 20px' }}>
                {result.certifications?.length > 0 && (
                  <div style={{ marginBottom: result.people_to_follow?.length ? 14 : 0 }}>
                    <p style={{ margin:'0 0 8px', fontSize:13, fontWeight:700 }}>🏅 Certifications worth doing</p>
                    <ul style={{ margin:0, paddingLeft:18, fontSize:13, color:'#444', lineHeight:1.7 }}>
                      {result.certifications.map((c, i) => <li key={i}>{c}</li>)}
                    </ul>
                  </div>
                )}
                {result.people_to_follow?.length > 0 && (
                  <div>
                    <p style={{ margin:'0 0 8px', fontSize:13, fontWeight:700 }}>👥 People to follow</p>
                    <ul style={{ margin:0, paddingLeft:18, fontSize:13, color:'#444', lineHeight:1.7 }}>
                      {result.people_to_follow.map((p, i) => <li key={i}>{p}</li>)}
                    </ul>
                  </div>
                )}
              </div>
            </div>

            {/* CTA */}
            <div style={{ background:'linear-gradient(135deg, #fff7ed, #fff)', border:'1px solid #fed7aa', borderRadius:14, padding:24, textAlign:'center' }}>
              <p style={{ margin:'0 0 6px', fontSize:16, fontWeight:700 }}>While you upskill, keep eyes on the market 👀</p>
              <p style={{ margin:'0 0 16px', fontSize:14, color:'#666' }}>Browse {form.targetRole} jobs and practice interviews now.</p>
              <div style={{ display:'flex', gap:10, justifyContent:'center', flexWrap:'wrap' }}>
                <a href={`/jobs/for/${form.targetRole.toLowerCase().replace(/\s+/g,'-')}`} style={{ background:'#ff6b00', color:'#fff', textDecoration:'none', padding:'10px 22px', borderRadius:10, fontSize:13, fontWeight:700 }}>Browse {form.targetRole} jobs →</a>
                <a href="/mock-interview" style={{ background:'#3b0764', color:'#fff', textDecoration:'none', padding:'10px 22px', borderRadius:10, fontSize:13, fontWeight:700 }}>🎙 Practice interviews</a>
                <a href="/salary-calculator" style={{ background:'#1d1d1f', color:'#fff', textDecoration:'none', padding:'10px 22px', borderRadius:10, fontSize:13, fontWeight:600 }}>💰 Estimate salary</a>
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  )
}
